### ISSUE TITLE
Formatting Documentation 

### ISSUE THREAD

**Issue by matthinrichsen-wf** [Workiva/go-rest#35]
It would be nice to be able to insert newlines into the generated documentation. For instance, if there are nested data structures newlines are not inserted - even if they are specified.

ie.
```
{
"value1:" 1,
"value2:" 2,
"value_map": 
   {
   "another_value": 1,
   "another_another_value": 2,
   "another_map": 
      {
      ...
      }
   }
}
```

Currently, the generated documentation formats it as the following:

```
{
"value1:" 1,
"value2:" 2,
"value_map": {"another_value": 1, "another_another_value": 2, "another_map": {...}}
}
```

**Comment by tylertreat-wf** [comment]
Assuming you're talking about the `DocString` field on `Rule`, you should be able to just use html markup.

**Comment by matthinrichsen-wf** [comment]
@tylertreat  Yes I am - that's awesome! I'll do that.
