### ISSUE TITLE
HTTP status codes for methods that are not implemented

### ISSUE THREAD

**Issue by aaronkavlie-wf** [Workiva/go-rest#37]
HTTP methods that are not implemented on a handler return a 501; 405 seems more appropriate for this.

501 is appropriate when the server does not support the method for **any resource**.

http://httpstatus.es/501

**Comment by tylertreat-wf** [comment]
Pretty sure this is actually a problem with gorilla/mux.

**Comment by aaronkavlie-wf** [comment]
It looks to be caused by the [NotImplemented error](https://github.com/Workiva/go-rest/blob/master/rest/errors.go#L63-66) which is the [default](https://github.com/Workiva/go-rest/blob/master/rest/base_handler.go#L103) for methods not overridden by the user.

**Comment by tylertreat-wf** [comment]
I stand corrected.

**Comment by tylertreat-wf** [comment]
Resolved in https://github.com/Workiva/go-rest/pull/38.
