### ISSUE TITLE
500 error for invalid JSON on POST request

### ISSUE THREAD

**Issue by aaronkavlie-wf** [Workiva/go-rest#41]
If the user submits invalid JSON on a POST request, it results in a 500 error. 400 is expected.

This is set explicitly in the [handleCreate method](https://github.com/Workiva/go-rest/blob/master/rest/handler.go#L138-L142).

[handleUpdateList](https://github.com/Workiva/go-rest/blob/master/rest/handler.go#L228-L237) sets the correct status code for invalid JSON.

**Comment by tylertreat-wf** [comment]
Resolved with https://github.com/Workiva/go-rest/pull/44.
