### ISSUE TITLE
ReadURI on GET override is registered to ReadListURI

### ISSUE THREAD

**Issue by johnlockwood-wf** [Workiva/go-rest#64]
@mikedonner-wf  I think this is why the python linking_client is getting 404 on loading links.
https://github.com/Workiva/go-rest/blob/master/rest%2Fapi.go#L312

**Comment by tylertreat-wf** [comment]
Hmmm... I think that should be:

```go
r.checkRoute("read override", h.ReadURI(), "OVERRIDE-GET", route)
```
