### ISSUE TITLE
Cannot serve on AppEngine

### ISSUE THREAD

**Issue by ericklaus-wf** [Workiva/go-rest#69]
It isn't possible to actually use go-rest on App Engine, since App Engine runs `http.ListenAndServe()` before a user module gets control.

We could get around this by providing providing a method that installs our router to the http module, or provide a method that exposes a base handler.

(Or maybe I'm missing something?)

*Install router*
```
func (r *muxAPI) HandleNow(middleware ...Middleware) {
    http.Handle("/", wrapMiddleware(r.router, middleware...))
}
```

*Expose handler*
```
func (r *muxAPI) RootHandler(middleware ...Middleware) http.Handler {
	return wrapMiddleware(r.router, middleware...)
}
```

**Comment by ericklaus-wf** [comment]
For what it's worth, I'm in favor of `HandleNow()` but I think it will complicate the documentation a bit.

**Comment by tylertreat-wf** [comment]
It should work in GAE. The go-rest `api` implements `http.Handler`, which you register in your `init`.

**Comment by ericklaus-wf** [comment]
Ah ha. So I just need to `http.Handle("/", api)`. That's a lot simpler than I imagined. Am I also missing a way to inject middleware in there?

**Comment by tylertreat-wf** [comment]
Doesn't look like there is a way for global middleware since that normally gets passed into `Start`. Might need to extend go-rest a bit for that.

**Comment by ericklaus-wf** [comment]
Are you interested in having that in go-rest? If so, I can work on a PR.

**Comment by tylertreat-wf** [comment]
Sure, PRs are welcome.
